import { 
  DemoWorkout, 
  DemoProgram, 
  DemoPersonalRecord, 
  DemoUserSettings,
  DEMO_USER 
} from './demoStore';

// Helper to get dates relative to today
function daysAgo(days: number): string {
  const date = new Date();
  date.setDate(date.getDate() - days);
  return date.toISOString().split('T')[0];
}

function daysFromNow(days: number): string {
  const date = new Date();
  date.setDate(date.getDate() + days);
  return date.toISOString().split('T')[0];
}

// Sample workouts with realistic exercise data
export const SAMPLE_WORKOUTS: DemoWorkout[] = [
  {
    id: 'workout-1',
    user_id: DEMO_USER.id,
    title: 'Push Day - Chest & Triceps',
    workout_date: daysAgo(1),
    duration_minutes: 65,
    notes: 'Great session! Felt strong on bench press.',
    status: 'completed',
    created_at: daysAgo(1),
    updated_at: daysAgo(1),
    exercises: [
      {
        id: 'ex-1-1',
        workout_id: 'workout-1',
        exercise_name: 'Barbell Bench Press',
        order_index: 0,
        notes: 'New PR!',
        created_at: daysAgo(1),
        sets: [
          { id: 'set-1-1-1', workout_exercise_id: 'ex-1-1', set_number: 1, weight: 60, reps: 10, rpe: 6, rir: 4, is_warmup: true, is_dropset: false, notes: null, created_at: daysAgo(1) },
          { id: 'set-1-1-2', workout_exercise_id: 'ex-1-1', set_number: 2, weight: 80, reps: 8, rpe: 7, rir: 3, is_warmup: false, is_dropset: false, notes: null, created_at: daysAgo(1) },
          { id: 'set-1-1-3', workout_exercise_id: 'ex-1-1', set_number: 3, weight: 90, reps: 6, rpe: 8, rir: 2, is_warmup: false, is_dropset: false, notes: null, created_at: daysAgo(1) },
          { id: 'set-1-1-4', workout_exercise_id: 'ex-1-1', set_number: 4, weight: 95, reps: 5, rpe: 9, rir: 1, is_warmup: false, is_dropset: false, notes: 'Felt heavy but good form', created_at: daysAgo(1) },
        ],
      },
      {
        id: 'ex-1-2',
        workout_id: 'workout-1',
        exercise_name: 'Incline Dumbbell Press',
        order_index: 1,
        notes: null,
        created_at: daysAgo(1),
        sets: [
          { id: 'set-1-2-1', workout_exercise_id: 'ex-1-2', set_number: 1, weight: 30, reps: 12, rpe: 7, rir: 3, is_warmup: false, is_dropset: false, notes: null, created_at: daysAgo(1) },
          { id: 'set-1-2-2', workout_exercise_id: 'ex-1-2', set_number: 2, weight: 30, reps: 10, rpe: 8, rir: 2, is_warmup: false, is_dropset: false, notes: null, created_at: daysAgo(1) },
          { id: 'set-1-2-3', workout_exercise_id: 'ex-1-2', set_number: 3, weight: 30, reps: 9, rpe: 9, rir: 1, is_warmup: false, is_dropset: false, notes: null, created_at: daysAgo(1) },
        ],
      },
      {
        id: 'ex-1-3',
        workout_id: 'workout-1',
        exercise_name: 'Tricep Pushdowns',
        order_index: 2,
        notes: null,
        created_at: daysAgo(1),
        sets: [
          { id: 'set-1-3-1', workout_exercise_id: 'ex-1-3', set_number: 1, weight: 25, reps: 15, rpe: 7, rir: 3, is_warmup: false, is_dropset: false, notes: null, created_at: daysAgo(1) },
          { id: 'set-1-3-2', workout_exercise_id: 'ex-1-3', set_number: 2, weight: 25, reps: 12, rpe: 8, rir: 2, is_warmup: false, is_dropset: false, notes: null, created_at: daysAgo(1) },
          { id: 'set-1-3-3', workout_exercise_id: 'ex-1-3', set_number: 3, weight: 25, reps: 10, rpe: 9, rir: 1, is_warmup: false, is_dropset: false, notes: null, created_at: daysAgo(1) },
        ],
      },
    ],
  },
  {
    id: 'workout-2',
    user_id: DEMO_USER.id,
    title: 'Pull Day - Back & Biceps',
    workout_date: daysAgo(3),
    duration_minutes: 70,
    notes: 'Focused on mind-muscle connection.',
    status: 'completed',
    created_at: daysAgo(3),
    updated_at: daysAgo(3),
    exercises: [
      {
        id: 'ex-2-1',
        workout_id: 'workout-2',
        exercise_name: 'Deadlift',
        order_index: 0,
        notes: null,
        created_at: daysAgo(3),
        sets: [
          { id: 'set-2-1-1', workout_exercise_id: 'ex-2-1', set_number: 1, weight: 100, reps: 5, rpe: 6, rir: 4, is_warmup: true, is_dropset: false, notes: null, created_at: daysAgo(3) },
          { id: 'set-2-1-2', workout_exercise_id: 'ex-2-1', set_number: 2, weight: 140, reps: 5, rpe: 7, rir: 3, is_warmup: false, is_dropset: false, notes: null, created_at: daysAgo(3) },
          { id: 'set-2-1-3', workout_exercise_id: 'ex-2-1', set_number: 3, weight: 160, reps: 3, rpe: 8, rir: 2, is_warmup: false, is_dropset: false, notes: null, created_at: daysAgo(3) },
          { id: 'set-2-1-4', workout_exercise_id: 'ex-2-1', set_number: 4, weight: 170, reps: 2, rpe: 9, rir: 1, is_warmup: false, is_dropset: false, notes: null, created_at: daysAgo(3) },
        ],
      },
      {
        id: 'ex-2-2',
        workout_id: 'workout-2',
        exercise_name: 'Pull-ups',
        order_index: 1,
        notes: null,
        created_at: daysAgo(3),
        sets: [
          { id: 'set-2-2-1', workout_exercise_id: 'ex-2-2', set_number: 1, weight: 0, reps: 10, rpe: 7, rir: 3, is_warmup: false, is_dropset: false, notes: null, created_at: daysAgo(3) },
          { id: 'set-2-2-2', workout_exercise_id: 'ex-2-2', set_number: 2, weight: 0, reps: 8, rpe: 8, rir: 2, is_warmup: false, is_dropset: false, notes: null, created_at: daysAgo(3) },
          { id: 'set-2-2-3', workout_exercise_id: 'ex-2-2', set_number: 3, weight: 0, reps: 7, rpe: 9, rir: 1, is_warmup: false, is_dropset: false, notes: null, created_at: daysAgo(3) },
        ],
      },
      {
        id: 'ex-2-3',
        workout_id: 'workout-2',
        exercise_name: 'Barbell Rows',
        order_index: 2,
        notes: null,
        created_at: daysAgo(3),
        sets: [
          { id: 'set-2-3-1', workout_exercise_id: 'ex-2-3', set_number: 1, weight: 70, reps: 10, rpe: 7, rir: 3, is_warmup: false, is_dropset: false, notes: null, created_at: daysAgo(3) },
          { id: 'set-2-3-2', workout_exercise_id: 'ex-2-3', set_number: 2, weight: 70, reps: 10, rpe: 8, rir: 2, is_warmup: false, is_dropset: false, notes: null, created_at: daysAgo(3) },
          { id: 'set-2-3-3', workout_exercise_id: 'ex-2-3', set_number: 3, weight: 70, reps: 8, rpe: 9, rir: 1, is_warmup: false, is_dropset: false, notes: null, created_at: daysAgo(3) },
        ],
      },
      {
        id: 'ex-2-4',
        workout_id: 'workout-2',
        exercise_name: 'Bicep Curls',
        order_index: 3,
        notes: null,
        created_at: daysAgo(3),
        sets: [
          { id: 'set-2-4-1', workout_exercise_id: 'ex-2-4', set_number: 1, weight: 15, reps: 12, rpe: 7, rir: 3, is_warmup: false, is_dropset: false, notes: null, created_at: daysAgo(3) },
          { id: 'set-2-4-2', workout_exercise_id: 'ex-2-4', set_number: 2, weight: 15, reps: 10, rpe: 8, rir: 2, is_warmup: false, is_dropset: false, notes: null, created_at: daysAgo(3) },
          { id: 'set-2-4-3', workout_exercise_id: 'ex-2-4', set_number: 3, weight: 15, reps: 8, rpe: 9, rir: 1, is_warmup: false, is_dropset: false, notes: null, created_at: daysAgo(3) },
        ],
      },
    ],
  },
  {
    id: 'workout-3',
    user_id: DEMO_USER.id,
    title: 'Leg Day',
    workout_date: daysAgo(5),
    duration_minutes: 75,
    notes: 'Legs were shaking after this one!',
    status: 'completed',
    created_at: daysAgo(5),
    updated_at: daysAgo(5),
    exercises: [
      {
        id: 'ex-3-1',
        workout_id: 'workout-3',
        exercise_name: 'Barbell Squat',
        order_index: 0,
        notes: null,
        created_at: daysAgo(5),
        sets: [
          { id: 'set-3-1-1', workout_exercise_id: 'ex-3-1', set_number: 1, weight: 60, reps: 10, rpe: 5, rir: 5, is_warmup: true, is_dropset: false, notes: null, created_at: daysAgo(5) },
          { id: 'set-3-1-2', workout_exercise_id: 'ex-3-1', set_number: 2, weight: 100, reps: 8, rpe: 7, rir: 3, is_warmup: false, is_dropset: false, notes: null, created_at: daysAgo(5) },
          { id: 'set-3-1-3', workout_exercise_id: 'ex-3-1', set_number: 3, weight: 120, reps: 6, rpe: 8, rir: 2, is_warmup: false, is_dropset: false, notes: null, created_at: daysAgo(5) },
          { id: 'set-3-1-4', workout_exercise_id: 'ex-3-1', set_number: 4, weight: 130, reps: 5, rpe: 9, rir: 1, is_warmup: false, is_dropset: false, notes: null, created_at: daysAgo(5) },
        ],
      },
      {
        id: 'ex-3-2',
        workout_id: 'workout-3',
        exercise_name: 'Romanian Deadlift',
        order_index: 1,
        notes: null,
        created_at: daysAgo(5),
        sets: [
          { id: 'set-3-2-1', workout_exercise_id: 'ex-3-2', set_number: 1, weight: 80, reps: 10, rpe: 7, rir: 3, is_warmup: false, is_dropset: false, notes: null, created_at: daysAgo(5) },
          { id: 'set-3-2-2', workout_exercise_id: 'ex-3-2', set_number: 2, weight: 80, reps: 10, rpe: 8, rir: 2, is_warmup: false, is_dropset: false, notes: null, created_at: daysAgo(5) },
          { id: 'set-3-2-3', workout_exercise_id: 'ex-3-2', set_number: 3, weight: 80, reps: 8, rpe: 9, rir: 1, is_warmup: false, is_dropset: false, notes: null, created_at: daysAgo(5) },
        ],
      },
      {
        id: 'ex-3-3',
        workout_id: 'workout-3',
        exercise_name: 'Leg Press',
        order_index: 2,
        notes: null,
        created_at: daysAgo(5),
        sets: [
          { id: 'set-3-3-1', workout_exercise_id: 'ex-3-3', set_number: 1, weight: 180, reps: 12, rpe: 7, rir: 3, is_warmup: false, is_dropset: false, notes: null, created_at: daysAgo(5) },
          { id: 'set-3-3-2', workout_exercise_id: 'ex-3-3', set_number: 2, weight: 200, reps: 10, rpe: 8, rir: 2, is_warmup: false, is_dropset: false, notes: null, created_at: daysAgo(5) },
          { id: 'set-3-3-3', workout_exercise_id: 'ex-3-3', set_number: 3, weight: 200, reps: 10, rpe: 9, rir: 1, is_warmup: false, is_dropset: false, notes: null, created_at: daysAgo(5) },
        ],
      },
    ],
  },
  {
    id: 'workout-4',
    user_id: DEMO_USER.id,
    title: 'Upper Body',
    workout_date: daysFromNow(1),
    duration_minutes: null,
    notes: 'Planned workout',
    status: 'planned',
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
    exercises: [
      {
        id: 'ex-4-1',
        workout_id: 'workout-4',
        exercise_name: 'Overhead Press',
        order_index: 0,
        notes: null,
        created_at: new Date().toISOString(),
        sets: [],
      },
      {
        id: 'ex-4-2',
        workout_id: 'workout-4',
        exercise_name: 'Lateral Raises',
        order_index: 1,
        notes: null,
        created_at: new Date().toISOString(),
        sets: [],
      },
    ],
  },
];

// Sample programs
export const SAMPLE_PROGRAMS: DemoProgram[] = [
  {
    id: 'program-1',
    user_id: DEMO_USER.id,
    name: 'Push Pull Legs',
    description: 'A classic 6-day PPL split for intermediate lifters. Great for building muscle and strength.',
    category: 'Hypertrophy',
    difficulty: 'intermediate',
    weeks: 8,
    days_per_week: 6,
    is_public: false,
    times_used: 12,
    created_at: daysAgo(30),
    updated_at: daysAgo(1),
    workouts: [
      {
        id: 'pw-1-1',
        program_id: 'program-1',
        name: 'Push A',
        day_number: 1,
        week_number: 1,
        order_index: 0,
        created_at: daysAgo(30),
        exercises: [
          { id: 'pe-1-1-1', program_workout_id: 'pw-1-1', exercise_name: 'Barbell Bench Press', target_sets: 4, target_reps: '6-8', rest_seconds: 180, order_index: 0, notes: null, created_at: daysAgo(30) },
          { id: 'pe-1-1-2', program_workout_id: 'pw-1-1', exercise_name: 'Overhead Press', target_sets: 3, target_reps: '8-10', rest_seconds: 120, order_index: 1, notes: null, created_at: daysAgo(30) },
          { id: 'pe-1-1-3', program_workout_id: 'pw-1-1', exercise_name: 'Incline Dumbbell Press', target_sets: 3, target_reps: '10-12', rest_seconds: 90, order_index: 2, notes: null, created_at: daysAgo(30) },
          { id: 'pe-1-1-4', program_workout_id: 'pw-1-1', exercise_name: 'Tricep Pushdowns', target_sets: 3, target_reps: '12-15', rest_seconds: 60, order_index: 3, notes: null, created_at: daysAgo(30) },
        ],
      },
      {
        id: 'pw-1-2',
        program_id: 'program-1',
        name: 'Pull A',
        day_number: 2,
        week_number: 1,
        order_index: 1,
        created_at: daysAgo(30),
        exercises: [
          { id: 'pe-1-2-1', program_workout_id: 'pw-1-2', exercise_name: 'Deadlift', target_sets: 4, target_reps: '5', rest_seconds: 180, order_index: 0, notes: null, created_at: daysAgo(30) },
          { id: 'pe-1-2-2', program_workout_id: 'pw-1-2', exercise_name: 'Pull-ups', target_sets: 3, target_reps: '8-10', rest_seconds: 120, order_index: 1, notes: null, created_at: daysAgo(30) },
          { id: 'pe-1-2-3', program_workout_id: 'pw-1-2', exercise_name: 'Barbell Rows', target_sets: 3, target_reps: '8-10', rest_seconds: 90, order_index: 2, notes: null, created_at: daysAgo(30) },
          { id: 'pe-1-2-4', program_workout_id: 'pw-1-2', exercise_name: 'Bicep Curls', target_sets: 3, target_reps: '12-15', rest_seconds: 60, order_index: 3, notes: null, created_at: daysAgo(30) },
        ],
      },
      {
        id: 'pw-1-3',
        program_id: 'program-1',
        name: 'Legs A',
        day_number: 3,
        week_number: 1,
        order_index: 2,
        created_at: daysAgo(30),
        exercises: [
          { id: 'pe-1-3-1', program_workout_id: 'pw-1-3', exercise_name: 'Barbell Squat', target_sets: 4, target_reps: '6-8', rest_seconds: 180, order_index: 0, notes: null, created_at: daysAgo(30) },
          { id: 'pe-1-3-2', program_workout_id: 'pw-1-3', exercise_name: 'Romanian Deadlift', target_sets: 3, target_reps: '8-10', rest_seconds: 120, order_index: 1, notes: null, created_at: daysAgo(30) },
          { id: 'pe-1-3-3', program_workout_id: 'pw-1-3', exercise_name: 'Leg Press', target_sets: 3, target_reps: '10-12', rest_seconds: 90, order_index: 2, notes: null, created_at: daysAgo(30) },
          { id: 'pe-1-3-4', program_workout_id: 'pw-1-3', exercise_name: 'Calf Raises', target_sets: 4, target_reps: '15-20', rest_seconds: 60, order_index: 3, notes: null, created_at: daysAgo(30) },
        ],
      },
      {
        id: 'pw-1-4',
        program_id: 'program-1',
        name: 'Push B',
        day_number: 4,
        week_number: 1,
        order_index: 3,
        created_at: daysAgo(30),
        exercises: [
          { id: 'pe-1-4-1', program_workout_id: 'pw-1-4', exercise_name: 'Overhead Press', target_sets: 4, target_reps: '6-8', rest_seconds: 180, order_index: 0, notes: null, created_at: daysAgo(30) },
          { id: 'pe-1-4-2', program_workout_id: 'pw-1-4', exercise_name: 'Incline Barbell Bench', target_sets: 3, target_reps: '8-10', rest_seconds: 120, order_index: 1, notes: null, created_at: daysAgo(30) },
          { id: 'pe-1-4-3', program_workout_id: 'pw-1-4', exercise_name: 'Dumbbell Flyes', target_sets: 3, target_reps: '12-15', rest_seconds: 90, order_index: 2, notes: null, created_at: daysAgo(30) },
          { id: 'pe-1-4-4', program_workout_id: 'pw-1-4', exercise_name: 'Lateral Raises', target_sets: 3, target_reps: '12-15', rest_seconds: 60, order_index: 3, notes: null, created_at: daysAgo(30) },
          { id: 'pe-1-4-5', program_workout_id: 'pw-1-4', exercise_name: 'Skull Crushers', target_sets: 3, target_reps: '10-12', rest_seconds: 60, order_index: 4, notes: null, created_at: daysAgo(30) },
        ],
      },
      {
        id: 'pw-1-5',
        program_id: 'program-1',
        name: 'Pull B',
        day_number: 5,
        week_number: 1,
        order_index: 4,
        created_at: daysAgo(30),
        exercises: [
          { id: 'pe-1-5-1', program_workout_id: 'pw-1-5', exercise_name: 'Barbell Rows', target_sets: 4, target_reps: '6-8', rest_seconds: 180, order_index: 0, notes: null, created_at: daysAgo(30) },
          { id: 'pe-1-5-2', program_workout_id: 'pw-1-5', exercise_name: 'Lat Pulldowns', target_sets: 3, target_reps: '10-12', rest_seconds: 120, order_index: 1, notes: null, created_at: daysAgo(30) },
          { id: 'pe-1-5-3', program_workout_id: 'pw-1-5', exercise_name: 'Seated Cable Rows', target_sets: 3, target_reps: '10-12', rest_seconds: 90, order_index: 2, notes: null, created_at: daysAgo(30) },
          { id: 'pe-1-5-4', program_workout_id: 'pw-1-5', exercise_name: 'Face Pulls', target_sets: 3, target_reps: '15-20', rest_seconds: 60, order_index: 3, notes: null, created_at: daysAgo(30) },
          { id: 'pe-1-5-5', program_workout_id: 'pw-1-5', exercise_name: 'Hammer Curls', target_sets: 3, target_reps: '10-12', rest_seconds: 60, order_index: 4, notes: null, created_at: daysAgo(30) },
        ],
      },
      {
        id: 'pw-1-6',
        program_id: 'program-1',
        name: 'Legs B',
        day_number: 6,
        week_number: 1,
        order_index: 5,
        created_at: daysAgo(30),
        exercises: [
          { id: 'pe-1-6-1', program_workout_id: 'pw-1-6', exercise_name: 'Front Squat', target_sets: 4, target_reps: '6-8', rest_seconds: 180, order_index: 0, notes: null, created_at: daysAgo(30) },
          { id: 'pe-1-6-2', program_workout_id: 'pw-1-6', exercise_name: 'Leg Press', target_sets: 3, target_reps: '10-12', rest_seconds: 120, order_index: 1, notes: null, created_at: daysAgo(30) },
          { id: 'pe-1-6-3', program_workout_id: 'pw-1-6', exercise_name: 'Leg Curls', target_sets: 3, target_reps: '10-12', rest_seconds: 90, order_index: 2, notes: null, created_at: daysAgo(30) },
          { id: 'pe-1-6-4', program_workout_id: 'pw-1-6', exercise_name: 'Leg Extensions', target_sets: 3, target_reps: '12-15', rest_seconds: 60, order_index: 3, notes: null, created_at: daysAgo(30) },
          { id: 'pe-1-6-5', program_workout_id: 'pw-1-6', exercise_name: 'Calf Raises', target_sets: 4, target_reps: '15-20', rest_seconds: 60, order_index: 4, notes: null, created_at: daysAgo(30) },
        ],
      },
    ],
  },
  {
    id: 'program-2',
    user_id: DEMO_USER.id,
    name: 'Starting Strength',
    description: 'A beginner-friendly 3-day full body program focused on building foundational strength.',
    category: 'Strength',
    difficulty: 'beginner',
    weeks: 12,
    days_per_week: 3,
    is_public: false,
    times_used: 5,
    created_at: daysAgo(60),
    updated_at: daysAgo(45),
    workouts: [
      {
        id: 'pw-2-1',
        program_id: 'program-2',
        name: 'Workout A',
        day_number: 1,
        week_number: 1,
        order_index: 0,
        created_at: daysAgo(60),
        exercises: [
          { id: 'pe-2-1-1', program_workout_id: 'pw-2-1', exercise_name: 'Barbell Squat', target_sets: 3, target_reps: '5', rest_seconds: 180, order_index: 0, notes: null, created_at: daysAgo(60) },
          { id: 'pe-2-1-2', program_workout_id: 'pw-2-1', exercise_name: 'Barbell Bench Press', target_sets: 3, target_reps: '5', rest_seconds: 180, order_index: 1, notes: null, created_at: daysAgo(60) },
          { id: 'pe-2-1-3', program_workout_id: 'pw-2-1', exercise_name: 'Deadlift', target_sets: 1, target_reps: '5', rest_seconds: 180, order_index: 2, notes: null, created_at: daysAgo(60) },
        ],
      },
      {
        id: 'pw-2-2',
        program_id: 'program-2',
        name: 'Workout B',
        day_number: 2,
        week_number: 1,
        order_index: 1,
        created_at: daysAgo(60),
        exercises: [
          { id: 'pe-2-2-1', program_workout_id: 'pw-2-2', exercise_name: 'Barbell Squat', target_sets: 3, target_reps: '5', rest_seconds: 180, order_index: 0, notes: null, created_at: daysAgo(60) },
          { id: 'pe-2-2-2', program_workout_id: 'pw-2-2', exercise_name: 'Overhead Press', target_sets: 3, target_reps: '5', rest_seconds: 180, order_index: 1, notes: null, created_at: daysAgo(60) },
          { id: 'pe-2-2-3', program_workout_id: 'pw-2-2', exercise_name: 'Barbell Rows', target_sets: 3, target_reps: '5', rest_seconds: 180, order_index: 2, notes: null, created_at: daysAgo(60) },
        ],
      },
    ],
  },
];

// Sample personal records
export const SAMPLE_PERSONAL_RECORDS: DemoPersonalRecord[] = [
  {
    id: 'pr-1',
    user_id: DEMO_USER.id,
    exercise_name: 'Barbell Bench Press',
    weight: 95,
    reps: 5,
    one_rep_max_estimate: 107,
    achieved_at: daysAgo(1),
    created_at: daysAgo(1),
  },
  {
    id: 'pr-2',
    user_id: DEMO_USER.id,
    exercise_name: 'Deadlift',
    weight: 170,
    reps: 2,
    one_rep_max_estimate: 180,
    achieved_at: daysAgo(3),
    created_at: daysAgo(3),
  },
  {
    id: 'pr-3',
    user_id: DEMO_USER.id,
    exercise_name: 'Barbell Squat',
    weight: 130,
    reps: 5,
    one_rep_max_estimate: 146,
    achieved_at: daysAgo(5),
    created_at: daysAgo(5),
  },
  {
    id: 'pr-4',
    user_id: DEMO_USER.id,
    exercise_name: 'Overhead Press',
    weight: 60,
    reps: 6,
    one_rep_max_estimate: 70,
    achieved_at: daysAgo(7),
    created_at: daysAgo(7),
  },
  {
    id: 'pr-5',
    user_id: DEMO_USER.id,
    exercise_name: 'Pull-ups',
    weight: 10, // Added weight
    reps: 8,
    one_rep_max_estimate: null,
    achieved_at: daysAgo(10),
    created_at: daysAgo(10),
  },
];

// Sample user settings
export const SAMPLE_USER_SETTINGS: DemoUserSettings = {
  id: 'settings-1',
  user_id: DEMO_USER.id,
  weight_unit: 'kg',
  theme: 'dark',
  timezone: Intl.DateTimeFormat().resolvedOptions().timeZone,
  notifications_enabled: true,
  email_workout_reminders: true,
  email_weekly_summary: false,
  created_at: daysAgo(30),
  updated_at: new Date().toISOString(),
};

// Exercise library for autocomplete
export const DEMO_EXERCISE_LIBRARY = [
  { name: 'Barbell Bench Press', category: 'Chest', equipment: 'Barbell', primary_muscles: ['Chest', 'Triceps', 'Front Deltoids'] },
  { name: 'Incline Barbell Bench', category: 'Chest', equipment: 'Barbell', primary_muscles: ['Upper Chest', 'Triceps', 'Front Deltoids'] },
  { name: 'Incline Dumbbell Press', category: 'Chest', equipment: 'Dumbbell', primary_muscles: ['Upper Chest', 'Triceps', 'Front Deltoids'] },
  { name: 'Dumbbell Flyes', category: 'Chest', equipment: 'Dumbbell', primary_muscles: ['Chest'] },
  { name: 'Cable Crossovers', category: 'Chest', equipment: 'Cable', primary_muscles: ['Chest'] },
  { name: 'Deadlift', category: 'Back', equipment: 'Barbell', primary_muscles: ['Back', 'Glutes', 'Hamstrings'] },
  { name: 'Pull-ups', category: 'Back', equipment: 'Bodyweight', primary_muscles: ['Lats', 'Biceps'] },
  { name: 'Barbell Rows', category: 'Back', equipment: 'Barbell', primary_muscles: ['Back', 'Biceps'] },
  { name: 'Lat Pulldowns', category: 'Back', equipment: 'Cable', primary_muscles: ['Lats', 'Biceps'] },
  { name: 'Seated Cable Rows', category: 'Back', equipment: 'Cable', primary_muscles: ['Back', 'Biceps'] },
  { name: 'Barbell Squat', category: 'Legs', equipment: 'Barbell', primary_muscles: ['Quadriceps', 'Glutes'] },
  { name: 'Front Squat', category: 'Legs', equipment: 'Barbell', primary_muscles: ['Quadriceps', 'Core'] },
  { name: 'Romanian Deadlift', category: 'Legs', equipment: 'Barbell', primary_muscles: ['Hamstrings', 'Glutes'] },
  { name: 'Leg Press', category: 'Legs', equipment: 'Machine', primary_muscles: ['Quadriceps', 'Glutes'] },
  { name: 'Leg Curls', category: 'Legs', equipment: 'Machine', primary_muscles: ['Hamstrings'] },
  { name: 'Leg Extensions', category: 'Legs', equipment: 'Machine', primary_muscles: ['Quadriceps'] },
  { name: 'Calf Raises', category: 'Legs', equipment: 'Machine', primary_muscles: ['Calves'] },
  { name: 'Overhead Press', category: 'Shoulders', equipment: 'Barbell', primary_muscles: ['Front Deltoids', 'Triceps'] },
  { name: 'Lateral Raises', category: 'Shoulders', equipment: 'Dumbbell', primary_muscles: ['Side Deltoids'] },
  { name: 'Face Pulls', category: 'Shoulders', equipment: 'Cable', primary_muscles: ['Rear Deltoids', 'Upper Back'] },
  { name: 'Bicep Curls', category: 'Arms', equipment: 'Dumbbell', primary_muscles: ['Biceps'] },
  { name: 'Hammer Curls', category: 'Arms', equipment: 'Dumbbell', primary_muscles: ['Biceps', 'Forearms'] },
  { name: 'Tricep Pushdowns', category: 'Arms', equipment: 'Cable', primary_muscles: ['Triceps'] },
  { name: 'Skull Crushers', category: 'Arms', equipment: 'Barbell', primary_muscles: ['Triceps'] },
  { name: 'Dips', category: 'Arms', equipment: 'Bodyweight', primary_muscles: ['Triceps', 'Chest'] },
];
